# Generated by Django 5.1.3 on 2024-11-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0002_imagem_servico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapa',
            name='localizacao',
        ),
        migrations.AddField(
            model_name='mapa',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='mapas/'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='url',
            field=models.ImageField(upload_to='imagens/'),
        ),
    ]
