# Generated by Django 5.1.3 on 2024-11-10 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0003_remove_mapa_localizacao_mapa_imagem_alter_imagem_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagem',
            old_name='url',
            new_name='imagem',
        ),
    ]
