# Generated by Django 4.2.5 on 2024-12-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0005_projeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagem',
            name='imagem',
        ),
        migrations.AddField(
            model_name='imagem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
    ]
