# Generated by Django 4.2.5 on 2024-12-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0006_remove_imagem_imagem_imagem_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagem',
            name='photo',
        ),
        migrations.AddField(
            model_name='imagem',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
    ]
